<?php
/**
 * Copyright (c) 2020 Peach Payments. All rights reserved. Developed by Francois Raubenheimer
 */
/** @var $this \PeachPayments\Hosted\Block\Redirect */
?>
<html lang="en">
<head>
    <title>Secure Payment</title>
    <style>
        body {
            background: #e9ecef;
        }
        .container {
            max-width: 684px;
            padding: 30px;
            background: #fff;
            border-radius: 8px;
            box-shadow: 0 0 1px 0 rgba(10, 31, 68, 0.08), 0 4px 20px 0 rgba(10, 31, 68, 0.1);
            margin: 5vh auto;
            text-align: center;
            font-size: 1.1em;
            color: #0A1F44;
        }
    </style>
</head>
<body>
<div class="container">
    <?php echo __('Completing payment, redirected to %1 momentarily.', $this->getRedirectUrl()); ?>
    <form id="redirect" style="display: none;" action="<?php echo $this->getRedirectUrl(); ?>" method="post">
        <?php foreach ($this->getFormData() as $key => $datum): ?>
            <input type="hidden" name="<?php echo $key; ?>" value="<?php echo $datum; ?>"/>
        <?php endforeach; ?>
    </form>
    <script type="application/javascript">
      document.getElementById('redirect').submit();
    </script>
</div>
</body>
</html>
